FORMAT: 1A
HOST: http://ais.reydifox.eu:5000

# AIS Blockchain API
**Team project** based on [Hyperledger fabric](https://hyperledger-fabric.readthedocs.io/) and [NodeJS](https://nodejs.org/).

# Group Get Started
<!-- include(get-started.md) -->

# Group Infrastructure
<!-- include(infrastructural-intro.md) -->

# Group API Reference: Infrastructure
<!-- include(infrastructural-api.md) -->

# Group WEB API
TODO