FORMAT: 1A
HOST: http://ais.reydifox.eu:5000

# AIS Blockchain API
**Team project** based on [Hyperledger fabric](https://hyperledger-fabric.readthedocs.io/) and [NodeJS](https://nodejs.org/).

# Group Get Started
<!-- include(get-started.md) -->

# Group API Reference: Infrastructure
We have developed a smart library, which helps application developers with CouchDB and Ledger interactions.
To use this library, just include the following code inside any javascript file in your NodeJS server.
```
const infrastructure = require('../fabcar/api/api.js');
```
<!-- include(infrastructural-api.md) -->

# Group WEB API
TODO